/* Autogenerated by png2wx.pl on Mon Nov 25 23:02:41 2019 */
#ifndef RACING_ICONS_H
#define RACING_ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_racing_logo_16;
extern wxBitmap *_img_racing_logo_32;

#endif /* RACING_ICONS_H */
